/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane197: THREE.Mesh;
    Plane197_1: THREE.Mesh;
  };
  materials: {
    cream_dark_wood: THREE.MeshStandardMaterial;
    cream_dark: THREE.MeshStandardMaterial;
  };
};

export function DesktopModel(
  props: JSX.IntrinsicElements["group"]
) {
  const { nodes, materials } = useGLTF(
    "/models/Desktop.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Plane197.geometry}
        material={materials.cream_dark_wood}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane197_1.geometry}
        material={materials.cream_dark}
      />
    </group>
  );
}

useGLTF.preload("/models/Desktop.glb");
