/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GenerateVideo } from "../Helpers/GenerateVideoTexture";

type GLTFResult = GLTF & {
  nodes: {
    Plane015: THREE.Mesh;
    Plane016: THREE.Mesh;
    Plane017: THREE.Mesh;
    Plane018: THREE.Mesh;
    Plane066: THREE.Mesh;
    Plane067: THREE.Mesh;
    Plane068: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane005_1: THREE.Mesh;
    Plane005_2: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane069: THREE.Mesh;
    Plane070: THREE.Mesh;
    Plane071: THREE.Mesh;
    Plane072: THREE.Mesh;
    Plane073: THREE.Mesh;
    Plane074: THREE.Mesh;
    Plane075: THREE.Mesh;
    Plane076: THREE.Mesh;
    Plane077: THREE.Mesh;
    Plane078: THREE.Mesh;
    Circle007: THREE.Mesh;
    Plane113: THREE.Mesh;
    Plane113_1: THREE.Mesh;
    Plane110: THREE.Mesh;
    Circle012: THREE.Mesh;
    Plane106: THREE.Mesh;
    Plane105: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Plane107: THREE.Mesh;
    Circle010: THREE.Mesh;
    Circle011: THREE.Mesh;
    Catenary006: THREE.Mesh;
    Catenary007: THREE.Mesh;
    Plane108: THREE.Mesh;
    Circle016: THREE.Mesh;
    Circle022_1: THREE.Mesh;
    Circle022_2: THREE.Mesh;
    Circle027: THREE.Mesh;
    Circle027_1: THREE.Mesh;
    Circle028: THREE.Mesh;
    Circle028_1: THREE.Mesh;
    Circle029: THREE.Mesh;
    Circle029_1: THREE.Mesh;
    Circle036: THREE.Mesh;
    Circle036_1: THREE.Mesh;
    Plane126: THREE.Mesh;
    Plane127: THREE.Mesh;
    Circle026: THREE.Mesh;
    Circle026_1: THREE.Mesh;
    Circle031: THREE.Mesh;
    Circle031_1: THREE.Mesh;
    Plane121: THREE.Mesh;
    PC_Window: THREE.Mesh;
    Circle006: THREE.Mesh;
    Plane218: THREE.Mesh;
  };
  materials: {
    cream_dark: THREE.MeshStandardMaterial;
    cream_yellow_light: THREE.MeshStandardMaterial;
    cream_grey: THREE.MeshStandardMaterial;
    cream_naranja_intenso: THREE.MeshStandardMaterial;
    cream_rosa_fuerte: THREE.MeshStandardMaterial;
    cream_verde_azulado_oscuro: THREE.MeshStandardMaterial;
    cream_grey_metallic: THREE.MeshStandardMaterial;
    cream_yellow: THREE.MeshStandardMaterial;
    cream_dark_wood: THREE.MeshStandardMaterial;
    cream_red: THREE.MeshStandardMaterial;
    cream_green: THREE.MeshStandardMaterial;
    postips: THREE.MeshStandardMaterial;
  };
};

export function HomeSecction(
  props: JSX.IntrinsicElements["group"]
) {
  const { nodes, materials } = useGLTF(
    "/models/HomeSecction.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name='Plane015'
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane016'
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane017'
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane018'
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane066'
        castShadow
        receiveShadow
        geometry={nodes.Plane066.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane067'
        castShadow
        receiveShadow
        geometry={nodes.Plane067.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane068'
        castShadow
        receiveShadow
        geometry={nodes.Plane068.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane005'
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.cream_yellow_light}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane006'
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.cream_grey}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane007'
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.cream_yellow_light}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane008'
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials.cream_grey}
        position={[0, 0, -3.02]}
      />
      <group name='Plane009' position={[0, 0, -3.02]}>
        <mesh
          name='Plane005_1'
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.cream_grey}
        />
        <mesh
          name='Plane005_2'
          castShadow
          receiveShadow
          geometry={nodes.Plane005_2.geometry}
          material={materials.cream_dark}
        />
      </group>
      <mesh
        name='Plane010'
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane011'
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane012'
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane013'
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane069'
        castShadow
        receiveShadow
        geometry={nodes.Plane069.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane070'
        castShadow
        receiveShadow
        geometry={nodes.Plane070.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane071'
        castShadow
        receiveShadow
        geometry={nodes.Plane071.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane072'
        castShadow
        receiveShadow
        geometry={nodes.Plane072.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane073'
        castShadow
        receiveShadow
        geometry={nodes.Plane073.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane074'
        castShadow
        receiveShadow
        geometry={nodes.Plane074.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane075'
        castShadow
        receiveShadow
        geometry={nodes.Plane075.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane076'
        castShadow
        receiveShadow
        geometry={nodes.Plane076.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane077'
        castShadow
        receiveShadow
        geometry={nodes.Plane077.geometry}
        material={materials.cream_naranja_intenso}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane078'
        castShadow
        receiveShadow
        geometry={nodes.Plane078.geometry}
        material={nodes.Plane078.material}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Circle007'
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={materials.cream_yellow_light}
        position={[0, 0, -3.02]}
      />
      <group name='Plane109' position={[0, 0, -3.02]}>
        <mesh
          name='Plane113'
          castShadow
          receiveShadow
          geometry={nodes.Plane113.geometry}
          material={materials.cream_yellow_light}
        />
        <mesh
          name='Plane113_1'
          castShadow
          receiveShadow
          geometry={nodes.Plane113_1.geometry}
          material={materials.cream_dark}
        />
      </group>
      <mesh
        name='Plane110'
        castShadow
        receiveShadow
        geometry={nodes.Plane110.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Circle012'
        castShadow
        receiveShadow
        geometry={nodes.Circle012.geometry}
        material={materials.cream_rosa_fuerte}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane106'
        castShadow
        receiveShadow
        geometry={nodes.Plane106.geometry}
        material={materials.cream_yellow_light}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane105'
        castShadow
        receiveShadow
        geometry={nodes.Plane105.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Sphere003'
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane107'
        castShadow
        receiveShadow
        geometry={nodes.Plane107.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Circle010'
        castShadow
        receiveShadow
        geometry={nodes.Circle010.geometry}
        material={materials.cream_rosa_fuerte}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Circle011'
        castShadow
        receiveShadow
        geometry={nodes.Circle011.geometry}
        material={materials.cream_verde_azulado_oscuro}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Catenary006'
        castShadow
        receiveShadow
        geometry={nodes.Catenary006.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Catenary007'
        castShadow
        receiveShadow
        geometry={nodes.Catenary007.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane108'
        castShadow
        receiveShadow
        geometry={nodes.Plane108.geometry}
        material={materials.cream_dark}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Circle016'
        castShadow
        receiveShadow
        geometry={nodes.Circle016.geometry}
        material={materials.cream_grey_metallic}
        position={[0, 0, -3.02]}
      />
      <group name='Circle019' position={[0, 0, -3.02]}>
        <mesh
          name='Circle022_1'
          castShadow
          receiveShadow
          geometry={nodes.Circle022_1.geometry}
          material={materials.cream_grey}
        />
        <mesh
          name='Circle022_2'
          castShadow
          receiveShadow
          geometry={nodes.Circle022_2.geometry}
          material={materials.cream_dark}
        />
      </group>
      <group name='Circle017' position={[0, 0, -3.02]}>
        <mesh
          name='Circle027'
          castShadow
          receiveShadow
          geometry={nodes.Circle027.geometry}
          material={materials.cream_grey}
        />
        <mesh
          name='Circle027_1'
          castShadow
          receiveShadow
          geometry={nodes.Circle027_1.geometry}
          material={materials.cream_verde_azulado_oscuro}
        />
      </group>
      <group name='Circle018' position={[0, 0, -3.02]}>
        <mesh
          name='Circle028'
          castShadow
          receiveShadow
          geometry={nodes.Circle028.geometry}
          material={materials.cream_grey}
        />
        <mesh
          name='Circle028_1'
          castShadow
          receiveShadow
          geometry={nodes.Circle028_1.geometry}
          material={materials.cream_yellow}
        />
      </group>
      <group name='Circle022' position={[0, 0, -3.02]}>
        <mesh
          name='Circle029'
          castShadow
          receiveShadow
          geometry={nodes.Circle029.geometry}
          material={materials.cream_grey}
        />
        <mesh
          name='Circle029_1'
          castShadow
          receiveShadow
          geometry={nodes.Circle029_1.geometry}
          material={materials.cream_rosa_fuerte}
        />
      </group>
      <group name='Tarro' position={[0, 0, -3.02]}>
        <mesh
          name='Circle036'
          castShadow
          receiveShadow
          geometry={nodes.Circle036.geometry}
          material={materials.cream_grey_metallic}
        />
        <mesh
          name='Circle036_1'
          castShadow
          receiveShadow
          geometry={nodes.Circle036_1.geometry}
          material={materials.cream_dark_wood}
        />
      </group>
      <mesh
        name='Plane126'
        castShadow
        receiveShadow
        geometry={nodes.Plane126.geometry}
        material={materials.cream_grey_metallic}
        position={[6.61, 3.29, -8.86]}
        rotation={[-Math.PI, 0.2, 0]}
        scale={[0.59, 1.97, 1.97]}
      />
      <mesh
        name='Plane127'
        castShadow
        receiveShadow
        geometry={nodes.Plane127.geometry}
        material={materials.cream_grey_metallic}
        position={[5.75, 3.29, -4.59]}
        rotation={[-Math.PI, 0.2, 0]}
        scale={[0.52, 1.28, 0.96]}
      />
      <group
        name='Circle020'
        position={[5.75, 3.29, -4.59]}
        rotation={[Math.PI / 2, 0, 0.2]}
        scale={0.29}>
        <mesh
          name='Circle026'
          castShadow
          receiveShadow
          geometry={nodes.Circle026.geometry}
          material={materials.cream_dark}
        />
        <mesh
          name='Circle026_1'
          castShadow
          receiveShadow
          geometry={nodes.Circle026_1.geometry}
          material={materials.cream_grey_metallic}
        />
      </group>
      <group name='Circle048' position={[0, 0, -3.02]}>
        <mesh
          name='Circle031'
          castShadow
          receiveShadow
          geometry={nodes.Circle031.geometry}
          material={materials.cream_red}
        />
        <mesh
          name='Circle031_1'
          castShadow
          receiveShadow
          geometry={nodes.Circle031_1.geometry}
          material={materials.cream_dark_wood}
        />
      </group>
      <mesh
        name='Plane121'
        castShadow
        receiveShadow
        geometry={nodes.Plane121.geometry}
        material={materials.cream_green}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='PC_Window'
        castShadow
        receiveShadow
        geometry={nodes.PC_Window.geometry}
        material={GenerateVideo("/videos/init.mp4")}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Circle006'
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={materials.cream_grey}
        position={[0, 0, -3.02]}
      />
      <mesh
        name='Plane218'
        castShadow
        receiveShadow
        geometry={nodes.Plane218.geometry}
        material={materials.postips}
        position={[0, 0, -3.02]}
      />
    </group>
  );
}

useGLTF.preload("/models/HomeSecction.glb");
