/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane141: THREE.Mesh;
    Plane142: THREE.Mesh;
    Plane143: THREE.Mesh;
    Circle033: THREE.Mesh;
    Circle034: THREE.Mesh;
    Plane259: THREE.Mesh;
    Plane260: THREE.Mesh;
    Circle106: THREE.Mesh;
    Circle106_1: THREE.Mesh;
    Circle113: THREE.Mesh;
    Circle113_1: THREE.Mesh;
    Circle113_2: THREE.Mesh;
    Circle113_3: THREE.Mesh;
    Plane293: THREE.Mesh;
    Plane293_1: THREE.Mesh;
    Plane293_2: THREE.Mesh;
    Plane293_3: THREE.Mesh;
    Plane159: THREE.Mesh;
    Plane280: THREE.Mesh;
  };
  materials: {
    cream_dark: THREE.MeshStandardMaterial;
    cream_dark_lighter: THREE.MeshStandardMaterial;
    cream_naranja_intenso: THREE.MeshStandardMaterial;
    cream_paper_kraft: THREE.MeshStandardMaterial;
    cream_verde_azulado_oscuro: THREE.MeshStandardMaterial;
    cream_dark_wood: THREE.MeshStandardMaterial;
    cream_yellow_light: THREE.MeshStandardMaterial;
    cream_green_dark: THREE.MeshStandardMaterial;
    cream_yellow: THREE.MeshStandardMaterial;
    cream_grey: THREE.MeshStandardMaterial;
    cream_yellow_dark: THREE.MeshStandardMaterial;
    postips: THREE.MeshStandardMaterial;
    Cartigres: THREE.MeshStandardMaterial;
  };
};

export function ProjectSecction(
  props: JSX.IntrinsicElements["group"]
) {
  const { nodes, materials } = useGLTF(
    "/models/ProjectsSecction.glb"
  ) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='Plane141'
          castShadow
          receiveShadow
          geometry={nodes.Plane141.geometry}
          material={materials.cream_dark}
          position={[28.48, 0.54, 6]}
          scale={[1.46, 1.98, 1.46]}
        />
        <mesh
          name='Plane142'
          castShadow
          receiveShadow
          geometry={nodes.Plane142.geometry}
          material={materials.cream_dark}
          position={[28.48, 1.46, 5.96]}
          scale={[1.43, 1.98, 1.43]}
        />
        <mesh
          name='Plane143'
          castShadow
          receiveShadow
          geometry={nodes.Plane143.geometry}
          material={materials.cream_dark_lighter}
          position={[28.48, 2.73, 5.96]}
          scale={[1.43, 1.98, 1.43]}
        />
        <mesh
          name='Circle033'
          castShadow
          receiveShadow
          geometry={nodes.Circle033.geometry}
          material={materials.cream_naranja_intenso}
          position={[27.31, 1.19, 7.1]}
          scale={0.21}
        />
        <mesh
          name='Circle034'
          castShadow
          receiveShadow
          geometry={nodes.Circle034.geometry}
          material={materials.cream_dark_lighter}
          position={[27.31, 1.11, 7.1]}
          scale={0.21}
        />
        <mesh
          name='Plane259'
          castShadow
          receiveShadow
          geometry={nodes.Plane259.geometry}
          material={materials.cream_paper_kraft}
          position={[17.41, 1.72, -6.04]}
          scale={[11.35, 1, 2.92]}
        />
        <mesh
          name='Plane260'
          castShadow
          receiveShadow
          geometry={nodes.Plane260.geometry}
          material={materials.cream_verde_azulado_oscuro}
          position={[17.99, 1.81, -3.08]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.05, 0.4, 0.18]}
        />
        <group
          name='Circle042'
          position={[27.85, 0.69, -6.11]}
          scale={0.61}>
          <mesh
            name='Circle106'
            castShadow
            receiveShadow
            geometry={nodes.Circle106.geometry}
            material={materials.cream_dark_wood}
          />
          <mesh
            name='Circle106_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle106_1.geometry}
            material={materials.cream_dark}
          />
        </group>
        <group
          name='Circle092'
          position={[38.47, 2.02, -4.01]}
          scale={0.33}>
          <mesh
            name='Circle113'
            castShadow
            receiveShadow
            geometry={nodes.Circle113.geometry}
            material={materials.cream_yellow_light}
          />
          <mesh
            name='Circle113_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle113_1.geometry}
            material={materials.cream_green_dark}
          />
          <mesh
            name='Circle113_2'
            castShadow
            receiveShadow
            geometry={nodes.Circle113_2.geometry}
            material={materials.cream_yellow}
          />
          <mesh
            name='Circle113_3'
            castShadow
            receiveShadow
            geometry={nodes.Circle113_3.geometry}
            material={materials.cream_paper_kraft}
          />
        </group>
        <group
          name='Plane267'
          position={[21.44, 5.08, -6.06]}
          rotation={[Math.PI / 2, 0, 1.92]}>
          <mesh
            name='Plane293'
            castShadow
            receiveShadow
            geometry={nodes.Plane293.geometry}
            material={materials.cream_grey}
          />
          <mesh
            name='Plane293_1'
            castShadow
            receiveShadow
            geometry={nodes.Plane293_1.geometry}
            material={materials.cream_green_dark}
          />
          <mesh
            name='Plane293_2'
            castShadow
            receiveShadow
            geometry={nodes.Plane293_2.geometry}
            material={materials.cream_yellow_dark}
          />
          <mesh
            name='Plane293_3'
            castShadow
            receiveShadow
            geometry={nodes.Plane293_3.geometry}
            material={materials.cream_dark}
          />
        </group>
        <mesh
          name='Plane159'
          castShadow
          receiveShadow
          geometry={nodes.Plane159.geometry}
          material={materials.postips}
          position={[26.37, 5.21, -5.65]}
          rotation={[0.14, 0.09, 0.02]}
        />
        <mesh
          name='Plane280'
          castShadow
          receiveShadow
          geometry={nodes.Plane280.geometry}
          material={materials.Cartigres}
          position={[0, -0.04, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ProjectsSecction.glb");
