/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube011_1: THREE.Mesh;
    Cube011_2: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    Cube008_3: THREE.Mesh;
    Cube008_4: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    Cube009_2: THREE.Mesh;
    Cube009_3: THREE.Mesh;
    Text: THREE.Mesh;
    Text001: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    Cube010_2: THREE.Mesh;
    Cube010_3: THREE.Mesh;
    Cube010_4: THREE.Mesh;
    Plane138: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube004_1: THREE.Mesh;
    Cube004_2: THREE.Mesh;
    Plane139: THREE.Mesh;
    Plane140: THREE.Mesh;
    Circle028: THREE.Mesh;
    Circle030: THREE.Mesh;
    Vert: THREE.Mesh;
    Vert001: THREE.Mesh;
    Text006: THREE.Mesh;
    Vert002: THREE.Mesh;
    Vert003: THREE.Mesh;
    Plane128: THREE.Mesh;
    Plane128_1: THREE.Mesh;
    Plane128_2: THREE.Mesh;
    Plane128_3: THREE.Mesh;
    Plane128_4: THREE.Mesh;
    Circle021: THREE.Mesh;
    Circle021_1: THREE.Mesh;
    Vert005_1: THREE.Mesh;
    Vert005_2: THREE.Mesh;
    Plane116: THREE.Mesh;
    Plane107: THREE.Mesh;
    Plane107_1: THREE.Mesh;
    Circle038: THREE.Mesh;
    Circle039: THREE.Mesh;
    Circle040: THREE.Mesh;
    Text007: THREE.Mesh;
    Circle047: THREE.Mesh;
    Plane117: THREE.Mesh;
    Game_Boy_Window: THREE.Mesh;
  };
  materials: {
    cream_dark_wood: THREE.MeshStandardMaterial;
    cream_dark_blue: THREE.MeshStandardMaterial;
    cream_morado: THREE.MeshStandardMaterial;
    cream_dark: THREE.MeshStandardMaterial;
    cream_yellow: THREE.MeshStandardMaterial;
    cream_verde_azulado_oscuro: THREE.MeshStandardMaterial;
    cream_green: THREE.MeshStandardMaterial;
    cream_naranja_intenso: THREE.MeshStandardMaterial;
    cream_rosa_fuerte: THREE.MeshStandardMaterial;
    cream_yellow_light: THREE.MeshStandardMaterial;
    cream_red: THREE.MeshStandardMaterial;
  };
};

export function TechsSecction(
  props: JSX.IntrinsicElements["group"]
) {
  const { nodes, materials } = useGLTF(
    "/models/TechsSecction.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name='Cube008'
        position={[58.96, 2, -6.3]}
        rotation={[0, -0.68, 0]}>
        <mesh
          name='Cube011_1'
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials.cream_dark_wood}
        />
        <mesh
          name='Cube011_2'
          castShadow
          receiveShadow
          geometry={nodes.Cube011_2.geometry}
          material={materials.cream_dark_blue}
        />
      </group>
      <group
        name='Cube010'
        position={[49.26, 5.99, -6.73]}
        rotation={[0, -0.49, 0]}>
        <mesh
          name='Cube008_1'
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials.cream_dark_wood}
        />
        <mesh
          name='Cube008_2'
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials.cream_morado}
        />
        <mesh
          name='Cube008_3'
          castShadow
          receiveShadow
          geometry={nodes.Cube008_3.geometry}
          material={materials.cream_dark}
        />
        <mesh
          name='Cube008_4'
          castShadow
          receiveShadow
          geometry={nodes.Cube008_4.geometry}
          material={materials.cream_dark_blue}
        />
      </group>
      <group
        name='Cube011'
        position={[55.45, 6.03, -7.12]}
        rotation={[0, -0.68, 0]}>
        <mesh
          name='Cube009'
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.cream_dark_wood}
        />
        <mesh
          name='Cube009_1'
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.cream_dark}
        />
        <mesh
          name='Cube009_2'
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials.cream_morado}
        />
        <mesh
          name='Cube009_3'
          castShadow
          receiveShadow
          geometry={nodes.Cube009_3.geometry}
          material={materials.cream_dark_blue}
        />
      </group>
      <mesh
        name='Text'
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[45.66, 1.99, -5.08]}
        rotation={[Math.PI / 2, 0, 0.45]}
        scale={3.12}
      />
      <mesh
        name='Text001'
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[48.37, 1.91, -5.95]}
        rotation={[Math.PI / 2, 0, -1.12]}
        scale={3.29}
      />
      <group
        name='Cube007'
        position={[46.63, 2, -6.82]}
        rotation={[0, -0.45, 0]}>
        <mesh
          name='Cube010_1'
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.cream_dark_wood}
        />
        <mesh
          name='Cube010_2'
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials.cream_yellow}
        />
        <mesh
          name='Cube010_3'
          castShadow
          receiveShadow
          geometry={nodes.Cube010_3.geometry}
          material={materials.cream_dark_blue}
        />
        <mesh
          name='Cube010_4'
          castShadow
          receiveShadow
          geometry={nodes.Cube010_4.geometry}
          material={materials.cream_verde_azulado_oscuro}
        />
      </group>
      <mesh
        name='Plane138'
        castShadow
        receiveShadow
        geometry={nodes.Plane138.geometry}
        material={nodes.Plane138.material}
        position={[46.63, 4.08, -6.86]}
        rotation={[-0.03, 1.35, 0.03]}
      />
      <group
        name='Cube006'
        position={[52.75, 2, -6.84]}
        rotation={[0, 0.4, 0]}>
        <mesh
          name='Cube004'
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.cream_dark_wood}
        />
        <mesh
          name='Cube004_1'
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.cream_dark_blue}
        />
        <mesh
          name='Cube004_2'
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials.cream_dark}
        />
      </group>
      <mesh
        name='Plane139'
        castShadow
        receiveShadow
        geometry={nodes.Plane139.geometry}
        material={nodes.Plane139.material}
        position={[53.62, 1.81, -5.1]}
        rotation={[Math.PI / 2, 0, -0.4]}
        scale={0.1}
      />
      <mesh
        name='Plane140'
        castShadow
        receiveShadow
        geometry={nodes.Plane140.geometry}
        material={nodes.Plane140.material}
        position={[51.1, 2.15, -5.79]}
        rotation={[0, 0.4, 0]}
      />
      <mesh
        name='Circle028'
        castShadow
        receiveShadow
        geometry={nodes.Circle028.geometry}
        material={nodes.Circle028.material}
        position={[52.74, 3.94, -6.83]}
        rotation={[0, 0.4, 0]}
      />
      <mesh
        name='Circle030'
        castShadow
        receiveShadow
        geometry={nodes.Circle030.geometry}
        material={nodes.Circle030.material}
        position={[49.25, 7.93, -6.74]}
        rotation={[0, -0.09, 0]}
      />
      <mesh
        name='Vert'
        castShadow
        receiveShadow
        geometry={nodes.Vert.geometry}
        material={nodes.Vert.material}
        position={[57.68, 2.14, -4.9]}
        rotation={[0, -0.68, 0]}
      />
      <mesh
        name='Vert001'
        castShadow
        receiveShadow
        geometry={nodes.Vert001.geometry}
        material={nodes.Vert001.material}
        position={[60.44, 1.98, -5.11]}
        rotation={[0, -0.68, 0]}
      />
      <mesh
        name='Text006'
        castShadow
        receiveShadow
        geometry={nodes.Text006.geometry}
        material={nodes.Text006.material}
        position={[48.22, 5.58, -5.11]}
        rotation={[Math.PI / 2, 0, 0.49]}
        scale={1.68}
      />
      <mesh
        name='Vert002'
        castShadow
        receiveShadow
        geometry={nodes.Vert002.geometry}
        material={nodes.Vert002.material}
        position={[58.96, 3.9, -6.3]}
        rotation={[0, -0.68, 0]}
      />
      <mesh
        name='Vert003'
        castShadow
        receiveShadow
        geometry={nodes.Vert003.geometry}
        material={nodes.Vert003.material}
        position={[51.05, 5.99, -5.78]}
        rotation={[0, -0.49, 0]}
      />
      <group
        name='Plane136'
        position={[55.38, 8.01, -7.1]}
        rotation={[-Math.PI / 2, 0, -0.68]}>
        <mesh
          name='Plane128'
          castShadow
          receiveShadow
          geometry={nodes.Plane128.geometry}
          material={materials.cream_verde_azulado_oscuro}
        />
        <mesh
          name='Plane128_1'
          castShadow
          receiveShadow
          geometry={nodes.Plane128_1.geometry}
          material={materials.cream_green}
        />
        <mesh
          name='Plane128_2'
          castShadow
          receiveShadow
          geometry={nodes.Plane128_2.geometry}
          material={materials.cream_morado}
        />
        <mesh
          name='Plane128_3'
          castShadow
          receiveShadow
          geometry={nodes.Plane128_3.geometry}
          material={materials.cream_naranja_intenso}
        />
        <mesh
          name='Plane128_4'
          castShadow
          receiveShadow
          geometry={nodes.Plane128_4.geometry}
          material={materials.cream_rosa_fuerte}
        />
      </group>
      <group
        name='Circle031'
        position={[57.07, 5.95, -6.03]}
        rotation={[0, -0.68, -Math.PI / 2]}
        scale={0.87}>
        <mesh
          name='Circle021'
          castShadow
          receiveShadow
          geometry={nodes.Circle021.geometry}
          material={materials.cream_naranja_intenso}
        />
        <mesh
          name='Circle021_1'
          castShadow
          receiveShadow
          geometry={nodes.Circle021_1.geometry}
          material={materials.cream_dark_blue}
        />
      </group>
      <group
        name='Vert005'
        position={[53.92, 7.06, -5.94]}
        rotation={[Math.PI / 2, 0, 0.68]}>
        <mesh
          name='Vert005_1'
          castShadow
          receiveShadow
          geometry={nodes.Vert005_1.geometry}
          material={materials.cream_dark_blue}
        />
        <mesh
          name='Vert005_2'
          castShadow
          receiveShadow
          geometry={nodes.Vert005_2.geometry}
          material={materials.cream_yellow}
        />
      </group>
      <mesh
        name='Plane116'
        geometry={nodes.Plane116.geometry}
        material={materials.cream_dark}
        position={[54.61, 0.94, 9.19]}
        rotation={[0, 0.42, 0]}
        scale={[0.53, 1, 0.17]}
      />
      <group
        name='Plane115'
        position={[54.87, 0.7, 6.8]}
        rotation={[0, 0.42, 0]}>
        <mesh
          name='Plane107'
          castShadow
          receiveShadow
          geometry={nodes.Plane107.geometry}
          material={materials.cream_yellow_light}
        />
        <mesh
          name='Plane107_1'
          castShadow
          receiveShadow
          geometry={nodes.Plane107_1.geometry}
          material={materials.cream_dark}
        />
      </group>
      <mesh
        name='Circle038'
        castShadow
        receiveShadow
        geometry={nodes.Circle038.geometry}
        material={materials.cream_yellow_light}
        position={[66.13, 0.14, -5.21]}
        scale={2.77}
      />
      <mesh
        name='Circle039'
        castShadow
        receiveShadow
        geometry={nodes.Circle039.geometry}
        material={materials.cream_red}
        position={[70.31, 1.59, -7.49]}
        rotation={[0, 0, -0.07]}
        scale={2.77}
      />
      <mesh
        name='Circle040'
        castShadow
        receiveShadow
        geometry={nodes.Circle040.geometry}
        material={materials.cream_red}
        position={[64.63, 1.57, -9.74]}
        rotation={[-0.04, 0, 0]}
        scale={2.77}
      />
      <mesh
        name='Text007'
        castShadow
        receiveShadow
        geometry={nodes.Text007.geometry}
        material={nodes.Text007.material}
        position={[47.55, 6.14, -7.6]}
        rotation={[Math.PI / 2, 0, 2.06]}
        scale={1.36}
      />
      <mesh
        name='Circle047'
        geometry={nodes.Circle047.geometry}
        material={materials.cream_red}
        position={[56.72, 0.95, 8.19]}
        rotation={[0, 0.42, 0]}
        scale={0.24}
      />
      <mesh
        name='Plane117'
        geometry={nodes.Plane117.geometry}
        material={materials.cream_dark}
        position={[56.06, 0.92, 9.54]}
        rotation={[0, 0.84, 0]}
        scale={[0.24, 0.24, 0.1]}
      />
      <mesh
        name='Game_Boy_Window'
        castShadow
        receiveShadow
        geometry={nodes.Game_Boy_Window.geometry}
        material={materials.cream_yellow_light}
        position={[54.87, 0.7, 6.8]}
        rotation={[0, 0.42, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/TechsSecction.glb");
