/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Pared: THREE.Mesh;
    Plane201: THREE.Mesh;
    Plane201_1: THREE.Mesh;
    Circle043: THREE.Mesh;
    Circle044: THREE.Mesh;
    Circle045: THREE.Mesh;
    Circle046: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
    Cylinder002_2: THREE.Mesh;
    Plane258: THREE.Mesh;
    Plane153: THREE.Mesh;
  };
  materials: {
    cream_yellow_light: THREE.MeshStandardMaterial;
    cream_grey_metallic: THREE.MeshStandardMaterial;
    cream_dark: THREE.MeshStandardMaterial;
    cream_dark_wood: THREE.MeshStandardMaterial;
    cream_naranja_intenso: THREE.MeshStandardMaterial;
    Posters: THREE.MeshStandardMaterial;
  };
};

export function Wall(
  props: JSX.IntrinsicElements["group"]
) {
  const { nodes, materials } = useGLTF(
    "/models/Wall.glb"
  ) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='Pared'
          castShadow
          receiveShadow
          geometry={nodes.Pared.geometry}
          material={materials.cream_yellow_light}
        />
        <group
          name='Plane114'
          position={[44.29, 5.78, -14.88]}>
          <mesh
            name='Plane201'
            castShadow
            receiveShadow
            geometry={nodes.Plane201.geometry}
            material={materials.cream_grey_metallic}
          />
          <mesh
            name='Plane201_1'
            castShadow
            receiveShadow
            geometry={nodes.Plane201_1.geometry}
            material={materials.cream_dark}
          />
        </group>
        <mesh
          name='Circle043'
          castShadow
          receiveShadow
          geometry={nodes.Circle043.geometry}
          material={materials.cream_dark_wood}
          position={[44.64, 5.03, 5.49]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.22}
        />
        <mesh
          name='Circle044'
          castShadow
          receiveShadow
          geometry={nodes.Circle044.geometry}
          material={materials.cream_dark_wood}
          position={[76.54, 5.03, 5.49]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.22}
        />
        <mesh
          name='Circle045'
          castShadow
          receiveShadow
          geometry={nodes.Circle045.geometry}
          material={materials.cream_dark_wood}
          position={[40.89, 11.22, -14.72]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.22}
        />
        <mesh
          name='Circle046'
          castShadow
          receiveShadow
          geometry={nodes.Circle046.geometry}
          material={materials.cream_dark_wood}
          position={[66.66, 11.22, -14.72]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.22}
        />
        <group
          name='Cylinder002'
          position={[54.86, 12.47, -14.73]}
          scale={0.53}>
          <mesh
            name='Cylinder002_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_1.geometry}
            material={materials.cream_naranja_intenso}
          />
          <mesh
            name='Cylinder002_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_2.geometry}
            material={materials.cream_grey_metallic}
          />
        </group>
        <mesh
          name='Plane258'
          castShadow
          receiveShadow
          geometry={nodes.Plane258.geometry}
          material={materials.cream_dark}
        />
        <mesh
          name='Plane153'
          castShadow
          receiveShadow
          geometry={nodes.Plane153.geometry}
          material={materials.Posters}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Wall.glb");
