/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Teapot: THREE.Mesh;
    Star: THREE.Mesh;
    Sponge: THREE.Mesh;
    Suzanne: THREE.Mesh;
    Plane118: THREE.Mesh;
    Button: THREE.Mesh;
    Plane111: THREE.Mesh;
  };
  materials: {
    cream_morado: THREE.MeshStandardMaterial;
    cream_yellow: THREE.MeshStandardMaterial;
    cream_dark_blue: THREE.MeshStandardMaterial;
    cream_naranja_intenso: THREE.MeshStandardMaterial;
    cream_grey: THREE.MeshStandardMaterial;
    cream_red: THREE.MeshStandardMaterial;
    postips: THREE.MeshStandardMaterial;
  };
};

export function YouTubeSecction(
  props: JSX.IntrinsicElements["group"]
) {
  const { nodes, materials } = useGLTF(
    "/models/YouTubeSecction.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name='Teapot'
        castShadow
        receiveShadow
        geometry={nodes.Teapot.geometry}
        material={materials.cream_morado}
        position={[72.19, -0.03, 6.07]}
      />
      <mesh
        name='Star'
        castShadow
        receiveShadow
        geometry={nodes.Star.geometry}
        material={materials.cream_yellow}
        position={[73.31, 0.82, 8.51]}
        rotation={[Math.PI / 2, -0.3, 0]}
      />
      <mesh
        name='Sponge'
        castShadow
        receiveShadow
        geometry={nodes.Sponge.geometry}
        material={materials.cream_dark_blue}
        position={[76.18, 0.99, 9.07]}
        rotation={[0, 0.38, 0]}
      />
      <mesh
        name='Suzanne'
        castShadow
        receiveShadow
        geometry={nodes.Suzanne.geometry}
        material={materials.cream_naranja_intenso}
        position={[67.81, 1.28, 9.82]}
        rotation={[-0.68, 0.49, 0.37]}
        scale={2.35}
      />
      <mesh
        name='Plane118'
        castShadow
        receiveShadow
        geometry={nodes.Plane118.geometry}
        material={materials.cream_grey}
        position={[72.22, -0.03, 10]}
        scale={1.29}
      />
      <mesh
        name='Button'
        castShadow
        receiveShadow
        geometry={nodes.Button.geometry}
        material={materials.cream_red}
        position={[73.09, 0.79, 10.75]}
        scale={0.76}
      />
      <mesh
        name='Plane111'
        castShadow
        receiveShadow
        geometry={nodes.Plane111.geometry}
        material={materials.postips}
        position={[86.5, 1.72, -6.2]}
        rotation={[0.14, 0.09, 0.02]}
      />
    </group>
  );
}

useGLTF.preload("/models/YouTubeSecction.glb");
