/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import {
  CylinderCollider,
  IcosphereCollider,
} from "../Utils/PhyshicsColliders";

type GLTFResult = GLTF & {
  nodes: {
    Circle038: THREE.Mesh;
    Circle038_1: THREE.Mesh;
    Circle038_2: THREE.Mesh;
    Circle041: THREE.Mesh;
    Circle041_1: THREE.Mesh;
    Circle041_2: THREE.Mesh;
    Circle044: THREE.Mesh;
    Circle044_1: THREE.Mesh;
    Circle044_2: THREE.Mesh;
    Circle046: THREE.Mesh;
    Circle046_1: THREE.Mesh;
    Circle046_2: THREE.Mesh;
    Sphere007: THREE.Mesh;
    Sphere007_1: THREE.Mesh;
    Sphere007_2: THREE.Mesh;
    Plane199: THREE.Mesh;
    Plane199_1: THREE.Mesh;
    Plane200: THREE.Mesh;
    Plane200_1: THREE.Mesh;
  };
  materials: {
    cream_verde_azulado_oscuro: THREE.MeshStandardMaterial;
    cream_yellow_light: THREE.MeshStandardMaterial;
    cream_dark_blue: THREE.MeshStandardMaterial;
    cream_rosa_fuerte: THREE.MeshStandardMaterial;
    cream_naranja_intenso: THREE.MeshStandardMaterial;
    cream_red: THREE.MeshStandardMaterial;
    cream_yellow: THREE.MeshStandardMaterial;
    cream_dark: THREE.MeshStandardMaterial;
    RedLight: THREE.MeshStandardMaterial;
    cream_dark_wood: THREE.MeshStandardMaterial;
    cream_grey_metallic: THREE.MeshStandardMaterial;
  };
};

export function TechsDynamics(
  props: JSX.IntrinsicElements["group"]
) {
  const { nodes, materials } = useGLTF(
    "/models/TechsSecctionDynamic.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <CylinderCollider
        id='ghost_1'
        args={[1, 1, 2.95, 30, 30]}
        scale={[0, 0, 0]}
        position={[41.21, 1.46, 5.95]}
        rotation={[0, 0, 0]}
        mass={1}
        type='Dynamic'>
        <group
          name='ghost_1'
          // position={[41.21, 1.46, 5.95]}
          // rotation={[0, 0.59, 0]}
        >
          <mesh
            name='Circle038'
            castShadow
            receiveShadow
            geometry={nodes.Circle038.geometry}
            material={materials.cream_verde_azulado_oscuro}
          />
          <mesh
            name='Circle038_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle038_1.geometry}
            material={materials.cream_yellow_light}
          />
          <mesh
            name='Circle038_2'
            castShadow
            receiveShadow
            geometry={nodes.Circle038_2.geometry}
            material={materials.cream_dark_blue}
          />
        </group>
      </CylinderCollider>

      <CylinderCollider
        id='ghost_1'
        args={[1, 1, 2.95, 30, 30]}
        scale={[0, 0, 0]}
        position={[43.1, 1.46, 4.4]}
        rotation={[0, 0.25, 0]}
        mass={1}
        type='Dynamic'>
        <group name='ghost_2'>
          <mesh
            name='Circle041'
            castShadow
            receiveShadow
            geometry={nodes.Circle041.geometry}
            material={materials.cream_rosa_fuerte}
          />
          <mesh
            name='Circle041_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle041_1.geometry}
            material={materials.cream_yellow_light}
          />
          <mesh
            name='Circle041_2'
            castShadow
            receiveShadow
            geometry={nodes.Circle041_2.geometry}
            material={materials.cream_dark_blue}
          />
        </group>
      </CylinderCollider>

      <CylinderCollider
        id='ghost_1'
        args={[1, 1, 2.95, 30, 30]}
        scale={[0, 0, 0]}
        position={[45.66, 1.46, 4.33]}
        rotation={[0, -0.38, 0]}
        mass={1}
        type='Dynamic'>
        <group name='ghost_3'>
          <mesh
            name='Circle044'
            castShadow
            receiveShadow
            geometry={nodes.Circle044.geometry}
            material={materials.cream_naranja_intenso}
          />
          <mesh
            name='Circle044_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle044_1.geometry}
            material={materials.cream_yellow_light}
          />
          <mesh
            name='Circle044_2'
            castShadow
            receiveShadow
            geometry={nodes.Circle044_2.geometry}
            material={materials.cream_dark_blue}
          />
        </group>
      </CylinderCollider>

      <CylinderCollider
        id='ghost_1'
        args={[1, 1, 2.95, 30, 30]}
        scale={[0, 0, 0]}
        position={[47.5, 1.46, 6.02]}
        rotation={[0, -0.51, 0]}
        mass={1}
        type='Dynamic'>
        <group name='ghost_4'>
          <mesh
            name='Circle046'
            castShadow
            receiveShadow
            geometry={nodes.Circle046.geometry}
            material={materials.cream_red}
          />
          <mesh
            name='Circle046_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle046_1.geometry}
            material={materials.cream_yellow_light}
          />
          <mesh
            name='Circle046_2'
            castShadow
            receiveShadow
            geometry={nodes.Circle046_2.geometry}
            material={materials.cream_dark_blue}
          />

          <group
            name='knife'
            position={[0.6447, -0.768858, 0.96357]}
            rotation={[Math.PI / 2, 0, -1.13]}
            scale={0.22}>
            <mesh
              name='Plane200'
              castShadow
              receiveShadow
              geometry={nodes.Plane200.geometry}
              material={materials.cream_dark_wood}
            />
            <mesh
              name='Plane200_1'
              castShadow
              receiveShadow
              geometry={nodes.Plane200_1.geometry}
              material={materials.cream_grey_metallic}
            />
          </group>
        </group>
      </CylinderCollider>

      <IcosphereCollider
        id='pacman'
        args={1.5}
        detail={2}
        scale={[1, 1, 1]}
        position={[44.18, 1.38, 8.2]}
        rotation={[-Math.PI, 0.47, 0]}
        mass={1}
        type='Dynamic'>
        <>
          <group name='pacman' scale={1.4}>
            <mesh
              name='Sphere007'
              castShadow
              receiveShadow
              geometry={nodes.Sphere007.geometry}
              material={materials.cream_yellow}
            />
            <mesh
              name='Sphere007_1'
              castShadow
              receiveShadow
              geometry={nodes.Sphere007_1.geometry}
              material={materials.cream_dark}
            />
            <mesh
              name='Sphere007_2'
              castShadow
              receiveShadow
              geometry={nodes.Sphere007_2.geometry}
              material={materials.RedLight}
            />
          </group>
          <group
            name='knife001'
            position={[-1, -1.3, -0.00467]}
            rotation={[-3.09, 0.31, 1.87]}
            scale={0.22}>
            <mesh
              name='Plane199'
              castShadow
              receiveShadow
              geometry={nodes.Plane199.geometry}
              material={materials.cream_dark_wood}
            />
            <mesh
              name='Plane199_1'
              castShadow
              receiveShadow
              geometry={nodes.Plane199_1.geometry}
              material={materials.cream_grey_metallic}
            />
          </group>
        </>
      </IcosphereCollider>
    </group>
  );
}

useGLTF.preload("/models/TechsSecctionDynamic.glb");
